#!/bin/bash

GRAPH_DIR=`dirname $0`
RESULT_EXPERIMENTS_DIR=$GRAPH_DIR/result_experiments
DATA_DIR=$GRAPH_DIR/data
IMAGE_DIR=$GRAPH_DIR/image
PLOT_DIR=$GRAPH_DIR/plot

function make_data {
    echo "make"
#for i in `ls $RESULT_EXPERIMENTS`; do
#    grep Total $RESULT_EXPERIMENTS/$i/1_block_size/*
#done
}

function plot {
    gnuplot -e "image_dir='$IMAGE_DIR'; data_dir='$DATA_DIR'" $PLOT_DIR/1_block_size.plt
    gnuplot -e "image_dir='$IMAGE_DIR'; data_dir='$DATA_DIR'" $PLOT_DIR/2_solid_vs_block.plt
    gnuplot -e "image_dir='$IMAGE_DIR'; data_dir='$DATA_DIR'" $PLOT_DIR/3_host_vs_gpu.plt
    gnuplot -e "image_dir='$IMAGE_DIR'; data_dir='$DATA_DIR'" $PLOT_DIR/4_mpiXgpu.plt
    gnuplot -e "image_dir='$IMAGE_DIR'; data_dir='$DATA_DIR'" $PLOT_DIR/5_scalability_lomonosov.plt
    gnuplot -e "image_dir='$IMAGE_DIR'; data_dir='$DATA_DIR'" $PLOT_DIR/6_sequence.plt
    #gnuplot $PLOT/gpuA.plt
    #gnuplot $PLOT/masAa.plt
}

make_data
plot
